template = "https://github.com/giellalt/template-lang-und"
rev_id = 287
template_sha = "15a8cf1917db1d48c56f7254ed58b4e74a6fcd9c"

[replacements]
__GLOTTOLOG_ID__ = "sout2965"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-slh"
__UND2C__ = "slh"
__UNDEFINED__ = "Southern Lushootseed"
__UND__ = "slh"
