template = "https://github.com/giellalt/template-lang-und"
rev_id = 302
template_sha = "b3740681672fe3b348eb75d3170f7a2da900a0b1"

[replacements]
__GLOTTOLOG_ID__ = "sout2965"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-slh"
__UND2C__ = "slh"
__UNDEFINED__ = "Southern Lushootseed"
__UND__ = "slh"
