template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "sout2965"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-slh"
__UND2C__ = "slh"
__UNDEFINED__ = "Southern Lushootseed"
__UND__ = "slh"
